# --- HIBERNATE / JPA ---
# usa update si quieres que cree/actualice tablas, o validate/none según tu caso
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://186.64.113.91:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=$$Eric5441$$
server.port=9090
# Configuración de Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true