# --- DATASOURCE ORACLE ---
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/orclpdb
spring.datasource.username=cuye
spring.datasource.password=cuye2025
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
server.port=9090

# --- HIBERNATE / JPA ---
# usa update si quieres que cree/actualice tablas, o validate/none según tu caso
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# --- HIKARI (opcional pero recomendable) ---
spring.datasource.hikari.pool-name=HikariPool-Oracle
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
